# Generated by Django 5.2.1 on 2025-05-17 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklending',
            old_name='borrower_date',
            new_name='borrowed_date',
        ),
        migrations.RemoveField(
            model_name='booklending',
            name='borrower_email',
        ),
        migrations.RemoveField(
            model_name='booklending',
            name='borrower_name',
        ),
        migrations.RemoveField(
            model_name='bookreservation',
            name='reserver_email',
        ),
        migrations.RemoveField(
            model_name='bookreservation',
            name='reserver_name',
        ),
        migrations.AddField(
            model_name='booklending',
            name='borrower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookreservation',
            name='reserver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_books', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
