# Generated by Django 5.2.1 on 2025-05-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'verbose_name': 'Book Copy', 'verbose_name_plural': 'Book Copies'},
        ),
    ]
